import {mkdtemp,readFile,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {spawnSync} from 'node:child_process';
const dir=await mkdtemp(join(tmpdir(),'ba-css-'));
try {
 const file=join(dir,'styles.css');
 const result=spawnSync('npm',['exec','--yes','--package=tailwindcss@3.4.17','--','tailwindcss','-i','scripts/ba-tailwind.css','-c','scripts/ba-tailwind.config.cjs','-o',file,'--minify'],{stdio:'inherit'});
 if(result.status!==0)throw Error('BA CSS build failed');
 await writeFile('berita-acara-gas/TailwindStyles.html','<!-- Generated by npm run build:ba-css; rebuild after changing BA classes. -->\n<style>\n'+await readFile(file,'utf8')+'\n</style>\n');
}finally{await rm(dir,{recursive:true,force:true});}
